server:
  port: 9005

spring:
   datasource:
      username: ${PV_DB_USERNAME}
      password: ${PV_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${PV_DB_HOST}:${PV_DB_PORT}/${PV_DB}
      type: com.zaxxer.hikari.HikariDataSource

      hikari:
          pool-name: pv_core_pool
          maximum-pool-size: 20
          hikari.max-lifetime: 1800000
          hikari.idle-timeout: 30000
   jpa:
     hibernate:
       ddl-auto: none

   flyway:
      schemas: core
      lockRetryCount: 100
      ignoreFutureMigrations: true
      defaultSchema: core

payvault:
    enviroment: ${PV_ENV}
